### ISSUE TITLE
[Question] `signature is missing ` occured

### ISSUE THREAD

**Issue by anencore94** [Mariatta/github_app_boilerplate#1]
Hi, Thanks for maintaining this awesome repository.
I've been following your [tutorial](https://github-app-tutorial.readthedocs.io/en/latest/responding-to-webhook.html) and now I've stucked after installing my github app to some repository, I encountered errors.

Here is the Heroku logs when I installed my Github App or Open pull request:
(The event triggered well but ValidationFailure occured)
```
2021-11-11T07:17:13.102277+00:00 app[web.1]: ======== Running on http://0.0.0.0:23512 ========
2021-11-11T07:17:13.102293+00:00 app[web.1]: (Press CTRL+C to quit)
2021-11-11T07:17:16.000000+00:00 app[api]: Build succeeded
2021-11-11T07:17:26.768972+00:00 heroku[router]: at=info method=POST path="/webhook" host=sample-github-app.herokuapp.com request_id=eba0b3a2-4584-4f65-aa41-7d8134084e0e fwd="140.82.115.117" dyno=web.1 connect=0ms service=3ms status=500 bytes=187 protocol=https
2021-11-11T07:17:26.767435+00:00 app[web.1]: Traceback (most recent call last):
2021-11-11T07:17:26.767446+00:00 app[web.1]: File "/app/webservice/__main__.py", line 30, in webhook
2021-11-11T07:17:26.767447+00:00 app[web.1]: event = sansio.Event.from_http(request.headers, body, secret=secret)
2021-11-11T07:17:26.767448+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gidgethub/sansio.py", line 122, in from_http
2021-11-11T07:17:26.767448+00:00 app[web.1]: raise ValidationFailure("signature is missing")
2021-11-11T07:17:26.767476+00:00 app[web.1]: gidgethub.ValidationFailure: signature is missing
```

Also, my github app's src code is as follows: https://github.com/anencore94/github_app_boilerplate

Could you find anything weird on my settings?

**Comment by Mariatta** [comment]
The error is raised by `gidgethub` library: https://github.com/brettcannon/gidgethub/blob/2a8f57f438a14cf3bb7b961d79b8562d37b0a6e8/gidgethub/sansio.py#L131-L132

It is expecting that the webhook payload from GitHub contains either the `"x-hub-signature-256"` or `"x-hub-signature"` header. The error is raised when the the header is missing. (documentation: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#delivery-headers)

When you configured the app and the webhook, did you specify the Webhook secret?

**Comment by anencore94** [comment]
Thanks for the rapid answer :) I thought I did it, but I should have go through from the scratch one more time to make sure.

**Comment by Mariatta** [comment]
First you'll need to add the secret on the GitHub App webhook, and then add the same secret as the `GH_SECRET` environment variable in Heroku.
